name: "Build"

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*.*.*'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 17 ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}

      - uses: gradle/gradle-build-action@v2

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.event_name == 'push' && github.event.ref_type == 'tag' }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17

     - uses: gradle/gradle-build-action@v2
       with:
         arguments: publish
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         CIVMC_NEXUS_USER: ${{ secrets.CIVMC_NEXUS_USER }}
         CIVMC_NEXUS_PASSWORD: ${{ secrets.CIVMC_NEXUS_PASSWORD }}